var app;

function loadVue() {
	app = new Vue({
	    el: "#app",
	    data: {
			player,
			tmp,
			format,
			formatWhole,
			formatWhether,
			formatTime,
			tab,
			subtab,
			tabData,
			getAutoAmt,
			getAutomatorCost,
			buyAuto,
			UPGS,
			buyUpg,
			hasUpg,
			checkFunc,
			getMaterialName,
			MATERIALS,
			MATERIAL_NAMES,
			hasMilestone,
			updateTemp,
			MILESTONES_AMT,
			MILESTONES,
			getNextSupercharged,
			hasSuperMilestone,
			canSuperCharge,
			superCharge,
			current_version,
			current_version_display,
			getSBUpgCost,
			getSBAutoCost,
			buySBAuto,
			ECLIPSE_REQ,
			apparatus_row_data,
			showTab,
			getMaterialColor,
			matColFromTitle,
			earlyMaterial,
			Decimal,
        }
	})
}