/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "Options": "选项",
    "Steel": "钢",
    "Unused Contraptions.": "未使用的装置。",
    "Offline Prod": "离线生产",
    "Main": "首页",
    "Cost": "成本",
    "Autosave": "自动保存",
    "slower": "更慢",
    "Speed: {{format(tmp.app.spd)}}x": "速度: {{format(tmp.app.spd)}}x",
    "Steel": "钢",
    "Super Batteries, which are increasing Super Charge gain by": "超级电池，增加超级充电增益",
    "Super Batteries/sec.": "超级电池/秒。",
    "Super Charge": "超级充电",
    "The Base Super Charge effect is raised": "基础超级充电效果提升",
    "UPGRADES": "升级",
    "You can Supercharge your Milestones by using Milestone Charge!": "您可以使用里程碑充电来增强您的里程碑！",
    "x Global Automator Speed": "x 全局自动化速度",
    "No more spending": "没有更多的开支",
    "of Steel's A1": "钢 A1",
    "Gold": "黄金",
    "Ionic Cores": "离子核心",
    "Eclipsal Power, which": "日食力量，其中",
    "Automator costs in later Materials increase": "后期材料中的自动机成本增加",
    "and multiplies Super Battery gain & Ion chance by": "并将超级电池增益和离子几率乘以",
    "All Super Battery Upgrade effects are multiplied by": "所有超级电池升级效果乘以",
    "All Material effects are multiplied by their amount": "所有材料效果都乘以其数量",
    "log2(A2)x A1 speed": "log2(A2)x A1 速度",
    "Milestone Charge": "里程碑充电",
    "Multiply Super Battery gain by": "将超级电池增益乘以",
    "makes Milestones multiply Automator speed by": "使里程碑乘以 自动器 速度",
    "makes Steel multiply Material gain by": "使钢铁乘以材料增益",
    "Multiply Super Battery gain by {{formatWhether(tmp.sbue2.plus(4).times(tmp.sbueMult))}}": "将超级电池增益乘以 {{formatWhether(tmp.sbue2.plus(4).times(tmp.sbueMult))}}",
    "Req: {{format(ECLIPSE_REQ)}} Steel": "需要: {{format(ECLIPSE_REQ)}} 钢",
    "Req: {{format(tmp.radResetReq)}} Super Batteries": "需要: {{format(tmp.radResetReq)}} 超级电池",
    "Reset all previous progress to increase the Eclipsal Lifespan by {{formatTime(tmp.ec.gain)}}": "重置所有先前的进度以将 日食 寿命增加 {{formatTime(tmp.ec.gain)}}",
    "Reset all Supercharger progress to gain an Ion Core": "重置所有超级充电进度以获得离子核心",
    "Post-100 scale 25% weaker": "Post-100比例 减弱25％",
    "Post-100 scale 50 later": "Post-100比例 50以后",
    "log2(A1)x Steel gain": "log2(A1)x 钢 增益",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'PATREON': 'PATREON',
    'DISCORD': 'DISCORD',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Currently: ": "当前: ",
    "Cost: ": "成本: ",
    "Ionic Boost": "离子加速",
    "Machines: ": "机器: ",
    "Reward: ": "奖励: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t\t\t\t\t": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^Next Ionic Boost: (.+) Ionic Cores$/, '下一个离子加速：$1 芯离子'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^A([\d\.]+): ([\d\.]+)$/, 'A$1：$2'],
	[/^([\d\.,]+) Steel$/, '$1 钢'],
	[/^([\d\.]+)x A1 speed$/, '$1x A1 速度'],
	[/^([\d\.]+)x Steel gain$/, '$1x 钢 增益'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);